[package]
name = "cruster"
version = "0.1.0"
edition = "2021"
authors = ["Sin Kettu"]
description = "Something between MitMProxy, Burp Suite/ZAP anf nuclei"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
futures = "0.3.19"
tui = { version = "0.17", default-features = false, features = ['termion', 'crossterm'] }
crossterm = "0.22.1"
rcgen = "0.8.14"
shellexpand = "2.1.0"